---
- name: install {{package_names}} with default package manager
  action: "{{backcompat_pkg_mgr}} name={{item}}"
  with_items: "package_names"
  sudo: yes
  when: backcompat_pkg_mgr == "yum" or backcompat_pkg_mgr == "apt"

# Handle dnf case for Fedora
- name: check if {{package_names}} exist
  command: rpm -q {{item}}
  with_items: "package_names"
  changed_when: False
  ignore_errors: True
  register: package_exists_results
  when: backcompat_pkg_mgr == "dnf"

# Use command since dnf was only added as a module in ansible 1.9.0
- name: install {{package_names}} with dnf
  command: dnf install -y {{item.1}}
  sudo: yes
  when: backcompat_pkg_mgr == "dnf" and {{item.0|failed}}
  with_together: 
  - package_exists_results.results
  - package_names
